### ISSUE TITLE
Questions & suggestions regarding current Tensorflow layer.

### ISSUE THREAD

**Issue by Jongchan** [dbbert/dfn#1]
First of all, nice work done.
I am much inspired by the 'Dynamic Filter Networks' paper, and I am planning to implement some ideas with dynamic filter layers in Tensorflow.

But first, I am trying to re-produce your results in my own way. Steerable filter was an easy single-channel example, and now I am trying to make a generalized version of dynamic filter layer...

I have several questions (and suggestions) for the [existing Tensorflow version layer](https://github.com/dbbert/dfn/blob/master/layers/dynamic_filter_layer_tensorflow.py).

1. Why is there assertion checking `assert num_filters_in <= 3`?
2. According to the current version, **the same filters** are used for **each channel**? ([code here](https://github.com/dbbert/dfn/blob/master/layers/dynamic_filter_layer_tensorflow.py#L26)). I think a generalized version, which apply different filters on different channels, can be made by setting `filter_size_prod=kernel_h*kernel_w*num_filters_in` and reshape the `reshape_filter` as size `(kernel_w, kernel_h, num_filters_in, filter_size_prod)`.
3. Are you planning to release the Tensorflow version soon? If so, when will you release the code?

Correct me if I am wrong or misunderstood your code.

**Comment by dbbert** [comment]
Hi Jongchan,
Thanks for your interest in our work. We are currently busy working for a deadline, I will get back to you next week!

**Comment by dbbert** [comment]
Hi Jongchan,

Sorry for the delay. I have implemented the steerable filters experiment in Tensorflow, you can find it in [this jupyter notebook](https://github.com/dbbert/dfn/blob/master/experiment_steerableFilter_tensorflow.ipynb).

This is a cleaner implementation than the Tensorflow layer I put in the repo before, so I will remove the old one. Let me know if you have any questions about the code!
