### ISSUE TITLE
missing bouncingMnist_originalTest.py file

### ISSUE THREAD

**Issue by ZhipengLiu6** [dbbert/dfn#2]
I read your excellent paper and run the code. I find there is not bouncingMnist_originalTest.py. I can get the  bouncingMnist_originalTest.py file easily by changing one line code "self.data_ = f['train'].value.reshape(-1, 28, 28)"  to "self.data_ = f['test'].value.reshape(-1, 28, 28)". Do I understand it right?  Thank you.

**Comment by dbbert** [comment]
Hi, I've uploaded the missing dataset_bouncingMnistOriginal_test.py file. You'll need to replace the path with the file downloaded from https://github.com/emansim/unsupervised-videos (wget http://www.cs.toronto.edu/~emansim/datasets/bouncing_mnist_test.npy).
