### ISSUE TITLE
bug in DisplayData

### ISSUE THREAD

**Issue by huangh12** [dbbert/dfn#5]
In dataset_bouncingMnistOriginal.py 
After GetBatch(), the dim of the data is  (16L, 1L, 64L, 64L, 20L), so you should use 
data = data[case_id, :].reshape(self.image_size_, self.image_size_, -1) 
in line149, instead of     
data = data[case_id, :].reshape(-1, self.image_size_, self.image_size_)
:)

**Comment by stephenjia** [comment]
When we visualize the data, we visualize the transposed data, such as the line 111 in train.py
batch_input = batch[..., :input_seqlen].transpose(0,4,2,3,1).squeeze(axis=4)
